static_resources:
  listeners:
    - name: main_listener
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10001
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: zone_aware_backend
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: zone_aware_backend
      connect_timeout: 1s
      type: STRICT_DNS
      lbPolicy: ROUND_ROBIN
      loadBalancingPolicy:
        policies:
          - typedExtensionConfig:
              name: envoy.load_balancing_policies.least_request
              typedConfig:
                "@type": type.googleapis.com/envoy.extensions.load_balancing_policies.least_request.v3.LeastRequest
                localityLbConfig:
                  zoneAwareLbConfig:
                    minClusterSize: "1"
                    locality_basis: ORCA_UTILIZATION
                    orca_metrics: ["application_utilization"]
                    orca_aggregation: AVERAGE
                    orca_fallback: EVEN_SPLIT
                    orca_min_reported_endpoints: { value: 1 }
                    orca_spillover_threshold: { value: 0.1 }
                    orca_update_interval: 2s
      load_assignment:
        cluster_name: zone_aware_backend
        endpoints:
          - locality:
              zone: us-east-1a
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8081
          - locality:
              zone: us-east-1b
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8082
    - name: demo-cluster
      type: STATIC
      connect_timeout: 1s
      load_assignment:
        cluster_name: demo-cluster
        endpoints:
          # This instance (zone-a)
          - locality:
              zone: us-east-1a
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 10001

          # Other instance (zone-b)
          - locality:
              zone: us-east-1b
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 10002
cluster_manager:
  local_cluster_name: demo-cluster
node:
  cluster: demo-cluster
  id: envoy-instance-1
  locality:
    zone: us-east-1a

admin:
  access_log_path: /tmp/envoy.admin.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
